export const fId = state => state.fId
export const scenicList = state => state.scenicList
export const camera = state => state.camera
export const F_Id = state => state.F_Id
export const smviewer = state => state.smviewer
export const scenicListAdd = state => state.scenicListAdd
export const monitorListAdd = state => state.monitorListAdd
export const csListAdd = state => state.csListAdd
export const zxistAdd = state => state.zxistAdd
export const wifiListAdd = state => state.wifiListAdd
export const fdListAdd = state => state.fdListAdd
export const isPack = state => state.isPack
export const isPackShow1 = state => state.isPackShow1
export const isPackShow2 = state => state.isPackShow2
export const isPackShow3 = state => state.isPackShow3
export const isTicket = state => state.isTicket
export const isTicketShow1 = state => state.isTicketShow1
export const isTicketShow2 = state => state.isTicketShow2
export const isMonitor = state => state.isMonitor
export const isMonitorShow1 = state => state.isMonitorShow1
export const isMonitorShow2 = state => state.isMonitorShow2
export const isMonitorShow3 = state => state.isMonitorShow3
