export default {
  fId: 0,
  scenicList: [],
  camera: {},
  F_Id: [],
  smviewer: {},
  videoList: [],
  scenicListAdd: [],
  monitorListAdd: [],
  csListAdd: [],
  zxistAdd: [],
  wifiListAdd: [],
  fdListAdd: [],
  isPack: false,
  isPackShow1: true,
  isPackShow2: true,
  isPackShow3: true,
  isTicket: false,
  isTicketShow1: true,
  isTicketShow2: true,
  isMonitor: false,
  isMonitorShow1: true,
  isMonitorShow3: true,
  isMonitorShow2: true,
}
